language: java
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.m2"
script: >-
  mvn -f ./splash.releng/pom.xml --global-settings ./.travis/settings.xml -DforceContextQualifier=$TRAVIS_BUILD_NUMBER
  && mvn -f ./splash.releng/pom.xml --global-settings ./.travis/settings.xml -DbuildBy="Travis CI - $TRAVIS_BUILD_WEB_URL"
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  target_branch: gh-pages
  on:
    branch: develop
  local_dir: "./bing-splash.update-site/target/repository"
  github_token: $GITHUB_TOKEN
env:
  secure: hSpQRuxjexenDnnuoZqOUZrjxn2RcFRDtJWBNr2U2fAwoiQTrowHUdR61FJEujP3Xc4e+91bWcEUH0hKodhwIrhpMezg+ps5vyxagmzFmv35/gEQ/NH3JsTkxG5fqQYmxT2SMed4qRpuby5pXiX0zXYR67vE75bui0dVyYnitKwEX7u5hb9HfyV0y3WAaKNeLjNjlY0UsGJQ536V/XEHhRg8PHE66yXhSb4jEIjT3p/AzpnmL14i9ZMO4va+vcZ4vLYr5ofwMEzbBbcfYue0AnNGWj0S/uVAod+tcyy5zaosEX9sU+jn49DJm9n65k+2MH4GI2wKGly4zyDt+08i/QgAVgj44Ne6TmO0JORMQ0sb7/X2kPitYKDleWokzJw81q/xPVrpLrWsgQEMJ5pVnvQ2hz+fSUT+B/Mspp97HV/zGkUYfPLoOIBommJdnzm8Fyfo1GTtsXtz/B8Y+sfrbsW7rYRzO6dYVcqZjLJ5zvePuQdBdpVfe/bXUcPdZ/u7ld1vRfORFvwd7PYrrVvvzv95hxwSqZ15Ds3SzoAihQmJ2/mC4EVVjw9AtbtcQL82oRPmXR4vFdLMsPO7qHTyoNrVRkqaVYvDzGWDwps49EUmvW0VT+VdLLzPaMwYdP29Ba2C+YHW0Amrvbutv+n61F4vAWVPW6gCKw4DrCIhyHM=
